apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    {{- include "chart.labels" . | indent 4 }}
data:
  name: {{ .Values.app.version | upper | quote }}
  {{- if eq .Values.env "production"}}
  paymentToken: "1234"
  {{- else }}
  {{- include "chart.labels" . | indent 2 }}
  paymentToken: false
  {{- end }}
  {{- with .Values.value.requirements.limits }}
  memory: {{ .memory }}
  cpu: {{ .cpu }}
  version: {{ $.Release.Name }}
  {{- end }}
  {{- $map := .Release.Name | upper | quote }}
  map: {{ $map }}
  users: |-
    {{- range tuple "Anton" "Vasia" }}
    - {{ . }}
    {{- end }}